<?php

namespace Ben\AssociationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CotisationController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/ubuntu/workspace/Association/app/cache/prod/jms_diextra/proxies/Ben-AssociationBundle-Controller-CotisationController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\AssociationBundle\\Controller\\CotisationController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'ajaxListAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy91e79413_b85238a8475be1296244d7b6bb2b5da373453321\__CG__\Ben\AssociationBundle\Controller\CotisationController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
