<?php

namespace Ben\AssociationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class configController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/ubuntu/workspace/Association/app/cache/prod/jms_diextra/proxies/Ben-AssociationBundle-Controller-configController.php';
        $f = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\AssociationBundle\\Controller\\configController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'updateLangAction' => array(0 => 'security.access.method_interceptor'), 'updateFiledsAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy91e79413_b9fe74137674bb3883fe7abd8500efc8d7ba892e\__CG__\Ben\AssociationBundle\Controller\configController();
        $instance->__CGInterception__setLoader($f);
        return $instance;
    }
}
