<?php

namespace Ben\AssociationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class eventController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/ubuntu/workspace/Association/app/cache/prod/jms_diextra/proxies/Ben-AssociationBundle-Controller-eventController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\AssociationBundle\\Controller\\eventController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'ajaxListAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'removeEntitiesAction' => array(0 => 'security.access.method_interceptor'), 'calendarAction' => array(0 => 'security.access.method_interceptor'), 'demoAction' => array(0 => 'security.access.method_interceptor'), 'sendAction' => array(0 => 'security.access.method_interceptor'), 'printAction' => array(0 => 'security.access.method_interceptor'), 'showJsonAction' => array(0 => 'security.access.method_interceptor'), 'updateDateAction' => array(0 => 'security.access.method_interceptor'), 'ftpAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy91e79413_d0b5eb6c22a2b05e513e250ecea2fc467254872b\__CG__\Ben\AssociationBundle\Controller\eventController();
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
