<?php

namespace Ben\MessageBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MessageController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/ubuntu/workspace/Association/app/cache/dev/jms_diextra/proxies/Ben-MessageBundle-Controller-MessageController.php';
        $i = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\MessageBundle\\Controller\\MessageController' => array('inboxAction' => array(0 => 'security.access.method_interceptor'), 'sentAction' => array(0 => 'security.access.method_interceptor'), 'deletedAction' => array(0 => 'security.access.method_interceptor'), 'threadAction' => array(0 => 'security.access.method_interceptor'), 'newThreadAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'searchAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxyef869ab2_d5ce9760c2504e370c891f42e7e44158534fa298\__CG__\Ben\MessageBundle\Controller\MessageController();
        $instance->__CGInterception__setLoader($i);
        return $instance;
    }
}
