<?php

namespace Ben\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/ubuntu/workspace/Association/app/cache/dev/jms_diextra/proxies/Ben-UserBundle-Controller-AdminController.php';
        $g = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\UserBundle\\Controller\\AdminController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'ajaxListAction' => array(0 => 'security.access.method_interceptor'), 'archiveAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'addAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'editMeAction' => array(0 => 'security.access.method_interceptor'), 'updateMeAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'removeUsersAction' => array(0 => 'security.access.method_interceptor'), 'setArchiveAction' => array(0 => 'security.access.method_interceptor'), 'enableUsersAction' => array(0 => 'security.access.method_interceptor'), 'setRoleAction' => array(0 => 'security.access.method_interceptor'), 'toCsvAction' => array(0 => 'security.access.method_interceptor'), 'toXmlAction' => array(0 => 'security.access.method_interceptor'), 'toPdfAction' => array(0 => 'security.access.method_interceptor'), 'printTicketAction' => array(0 => 'security.access.method_interceptor'), 'toExcelAction' => array(0 => 'security.access.method_interceptor'), 'logAction' => array(0 => 'security.access.method_interceptor'), 'publicAction' => array(0 => 'security.access.method_interceptor'), 'sendMailAction' => array(0 => 'security.access.method_interceptor'), 'alertMailAction' => array(0 => 'security.access.method_interceptor'), 'alertPrintAction' => array(0 => 'security.access.method_interceptor'), 'clearLogAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxyef869ab2_aaa968b903122828095fdfdbf82a8a9887fe7bb9\__CG__\Ben\UserBundle\Controller\AdminController();
        $instance->__CGInterception__setLoader($g);
        return $instance;
    }
}
