<?php

namespace Ben\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GroupController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/ubuntu/workspace/Association/app/cache/dev/jms_diextra/proxies/Ben-UserBundle-Controller-GroupController.php';
        $h = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ben\\UserBundle\\Controller\\GroupController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'addFilterGroupAction' => array(0 => 'security.access.method_interceptor'), 'addToGroupAction' => array(0 => 'security.access.method_interceptor'), 'removeFromGroupAction' => array(0 => 'security.access.method_interceptor'), 'logGroupAction' => array(0 => 'security.access.method_interceptor'), 'sendMailGroupAction' => array(0 => 'security.access.method_interceptor'), 'sendLetterAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxyef869ab2_209c1471bd4965eeea62c412a9a107b728cb3fa9\__CG__\Ben\UserBundle\Controller\GroupController();
        $instance->__CGInterception__setLoader($h);
        return $instance;
    }
}
