<?php

namespace Proxies\__CG__\Ben\MessageBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MessageMetadata extends \Ben\MessageBundle\Entity\MessageMetadata implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setMessage(\FOS\MessageBundle\Model\MessageInterface $message)
    {
        $this->__load();
        return parent::setMessage($message);
    }

    public function setParticipant(\FOS\MessageBundle\Model\ParticipantInterface $participant)
    {
        $this->__load();
        return parent::setParticipant($participant);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getMessage()
    {
        $this->__load();
        return parent::getMessage();
    }

    public function getParticipant()
    {
        $this->__load();
        return parent::getParticipant();
    }

    public function getIsRead()
    {
        $this->__load();
        return parent::getIsRead();
    }

    public function setIsRead($isRead)
    {
        $this->__load();
        return parent::setIsRead($isRead);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'isRead', 'id', 'message', 'participant');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}