<?php

namespace Proxies\__CG__\Ben\UserBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class profile extends \Ben\UserBundle\Entity\profile implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getFullName()
    {
        $this->__load();
        return parent::getFullName();
    }

    public function setFamilyName($familyName)
    {
        $this->__load();
        return parent::setFamilyName($familyName);
    }

    public function getFamilyName()
    {
        $this->__load();
        return parent::getFamilyName();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setBarcode($barcode)
    {
        $this->__load();
        return parent::setBarcode($barcode);
    }

    public function getBarcode()
    {
        $this->__load();
        return parent::getBarcode();
    }

    public function setCin($cin)
    {
        $this->__load();
        return parent::setCin($cin);
    }

    public function getCin()
    {
        $this->__load();
        return parent::getCin();
    }

    public function setBirthday($birthday)
    {
        $this->__load();
        return parent::setBirthday($birthday);
    }

    public function getBirthday()
    {
        $this->__load();
        return parent::getBirthday();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setAddress($address)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setJob($job)
    {
        $this->__load();
        return parent::setJob($job);
    }

    public function getJob()
    {
        $this->__load();
        return parent::getJob();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setWebsite($website)
    {
        $this->__load();
        return parent::setWebsite($website);
    }

    public function getWebsite()
    {
        $this->__load();
        return parent::getWebsite();
    }

    public function setFacebook($facebook)
    {
        $this->__load();
        return parent::setFacebook($facebook);
    }

    public function getFacebook()
    {
        $this->__load();
        return parent::getFacebook();
    }

    public function setGoogle($google)
    {
        $this->__load();
        return parent::setGoogle($google);
    }

    public function getGoogle()
    {
        $this->__load();
        return parent::getGoogle();
    }

    public function setTwitter($twitter)
    {
        $this->__load();
        return parent::setTwitter($twitter);
    }

    public function getTwitter()
    {
        $this->__load();
        return parent::getTwitter();
    }

    public function setImage(\Ben\AssociationBundle\Entity\image $image = NULL)
    {
        $this->__load();
        return parent::setImage($image);
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function setPostCode($post_code)
    {
        $this->__load();
        return parent::setPostCode($post_code);
    }

    public function getPostCode()
    {
        $this->__load();
        return parent::getPostCode();
    }

    public function setContry($contry)
    {
        $this->__load();
        return parent::setContry($contry);
    }

    public function getContry()
    {
        $this->__load();
        return parent::getContry();
    }

    public function setTel($tel)
    {
        $this->__load();
        return parent::setTel($tel);
    }

    public function getTel()
    {
        $this->__load();
        return parent::getTel();
    }

    public function setGsm($gsm)
    {
        $this->__load();
        return parent::setGsm($gsm);
    }

    public function getGsm()
    {
        $this->__load();
        return parent::getGsm();
    }

    public function setDiplome($diplome)
    {
        $this->__load();
        return parent::setDiplome($diplome);
    }

    public function getDiplome()
    {
        $this->__load();
        return parent::getDiplome();
    }

    public function setExpertise($expertise)
    {
        $this->__load();
        return parent::setExpertise($expertise);
    }

    public function getExpertise()
    {
        $this->__load();
        return parent::getExpertise();
    }

    public function setFrequence($frequence)
    {
        $this->__load();
        return parent::setFrequence($frequence);
    }

    public function getFrequence()
    {
        $this->__load();
        return parent::getFrequence();
    }

    public function getFrequenceLabel()
    {
        $this->__load();
        return parent::getFrequenceLabel();
    }

    public function setMethod($method)
    {
        $this->__load();
        return parent::setMethod($method);
    }

    public function getMethod()
    {
        $this->__load();
        return parent::getMethod();
    }

    public function setMontant($montant)
    {
        $this->__load();
        return parent::setMontant($montant);
    }

    public function getMontant()
    {
        $this->__load();
        return parent::getMontant();
    }

    public function setArchived($archived)
    {
        $this->__load();
        return parent::setArchived($archived);
    }

    public function isArchived()
    {
        $this->__load();
        return parent::isArchived();
    }

    public function setCause($cause)
    {
        $this->__load();
        return parent::setCause($cause);
    }

    public function getCause()
    {
        $this->__load();
        return parent::getCause();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'family_name', 'first_name', 'barcode', 'cin', 'birthday', 'gender', 'address', 'post_code', 'city', 'contry', 'job', 'tel', 'gsm', 'diplome', 'expertise', 'description', 'website', 'facebook', 'google', 'twitter', 'frequence', 'method', 'montant', 'archived', 'cause', 'image');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}