<?php

namespace Proxies\__CG__\Ben\AssociationBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Fields extends \Ben\AssociationBundle\Entity\Fields implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTableName($tableName)
    {
        $this->__load();
        return parent::setTableName($tableName);
    }

    public function getTableName()
    {
        $this->__load();
        return parent::getTableName();
    }

    public function setFieldName($fieldName)
    {
        $this->__load();
        return parent::setFieldName($fieldName);
    }

    public function getFieldName()
    {
        $this->__load();
        return parent::getFieldName();
    }

    public function setRequired($required)
    {
        $this->__load();
        return parent::setRequired($required);
    }

    public function getRequired()
    {
        $this->__load();
        return parent::getRequired();
    }

    public function setVisible($visible)
    {
        $this->__load();
        return parent::setVisible($visible);
    }

    public function getVisible()
    {
        $this->__load();
        return parent::getVisible();
    }

    public function isVisible()
    {
        $this->__load();
        return parent::isVisible();
    }

    public function setPosition($position)
    {
        $this->__load();
        return parent::setPosition($position);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setNicename($nicename)
    {
        $this->__load();
        return parent::setNicename($nicename);
    }

    public function getNicename()
    {
        $this->__load();
        return parent::getNicename();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'table_name', 'field_name', 'required', 'visible', 'position', 'nicename');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}