<?php

namespace Proxies\__CG__\Ben\MessageBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ThreadMetadata extends \Ben\MessageBundle\Entity\ThreadMetadata implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setThread(\FOS\MessageBundle\Model\ThreadInterface $thread)
    {
        $this->__load();
        return parent::setThread($thread);
    }

    public function setParticipant(\FOS\MessageBundle\Model\ParticipantInterface $participant)
    {
        $this->__load();
        return parent::setParticipant($participant);
    }

    public function getParticipant()
    {
        $this->__load();
        return parent::getParticipant();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getThread()
    {
        $this->__load();
        return parent::getThread();
    }

    public function getIsDeleted()
    {
        $this->__load();
        return parent::getIsDeleted();
    }

    public function setIsDeleted($isDeleted)
    {
        $this->__load();
        return parent::setIsDeleted($isDeleted);
    }

    public function getLastParticipantMessageDate()
    {
        $this->__load();
        return parent::getLastParticipantMessageDate();
    }

    public function setLastParticipantMessageDate(\DateTime $date)
    {
        $this->__load();
        return parent::setLastParticipantMessageDate($date);
    }

    public function getLastMessageDate()
    {
        $this->__load();
        return parent::getLastMessageDate();
    }

    public function setLastMessageDate(\DateTime $date)
    {
        $this->__load();
        return parent::setLastMessageDate($date);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'isDeleted', 'lastParticipantMessageDate', 'lastMessageDate', 'id', 'thread', 'participant');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}